const MAX_FILE_SIZE_MB = Number(process.env.MAX_FILE_SIZE_MB) || 500;
const MAX_FILE_COUNT = Number(process.env.MAX_FILE_COUNT) || 10;
const SESSION_EXPIRY_MINUTES = Number(process.env.SESSION_EXPIRY_MINUTES) || 10;
const CODE_LENGTH = Number(process.env.CODE_LENGTH) || 6;

const ERROR_CODES = {
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	TOO_MANY_FILES: "TOO_MANY_FILES",
	BLOCKED_FILE_TYPE: "BLOCKED_FILE_TYPE",
	NO_FILE_UPLOADED: "NO_FILE_UPLOADED",
	CODE_NOT_FOUND: "CODE_NOT_FOUND",
	TRANSFER_EXPIRED: "TRANSFER_EXPIRED",
	ALREADY_DOWNLOADED: "ALREADY_DOWNLOADED",
	INVALID_CODE: "INVALID_CODE",
	SERVER_ERROR: "SERVER_ERROR",
};

const CODE_REGEX = /^[A-Z2-9]{6}$/;

module.exports = {
	MAX_FILE_SIZE_MB,
	MAX_FILE_COUNT,
	SESSION_EXPIRY_MINUTES,
	CODE_LENGTH,
	ERROR_CODES,
	CODE_REGEX,
};

